name: Run Unit Test via Pytest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install pytest pytest-cov
      # - name: Lint with Ruff
      #   run: |
      #     pip install ruff
      #     ruff check --format=github --target-version=py312 .
      #   continue-on-error: true
      # - name: Check code formatting with Ruff
      #   run: ruff format --diff --target-version=py39
      #   continue-on-error: true
      - name: Test with pytest
        env:
          CI: true
        run: |
          source .venv/bin/activate
          pytest --doctest-modules --cov=threadman --cov-report=term
